### ISSUE TITLE
Publish tailscale-localapi to crates.io?

### ISSUE THREAD

**Issue by messense** [jtdowney/tailscale-proxy#1]
Cool project! I'm interested in using the `tailscale-localapi` crate, could you publish it to crates.io? Thanks in advance!

**Comment by jtdowney** [comment]
@messense I can do that. It is incomplete today (only unix sockets and only a few APIs) but I am happy to publish what I have.

**Comment by messense** [comment]
I plan to use it to fetch certificate pairs so it works for me already.

**Comment by jtdowney** [comment]
Sorry this took so long. I finally got back to this project, and it is now on crates at https://crates.io/crates/tailscale-localapi.
